drop table Person;

create table Person
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    name varchar(100),
    age  int
);

insert into Person (id, name, age) values (1, 'Test person', 20);

select * from Person;


create table Person
(
    id int PRIMARY KEY GENERATED BY DEFAULT as identity,
    name varchar(100) not null ,
    age int check ( age < 100 )
);

create table Item
(
    id int PRIMARY KEY GENERATED BY DEFAULT as identity,
    person_id int references Person(id) on DELETE set null ,
    item_name varchar(100) not null
);


insert into Person (name, age) VALUES ('Tom', 35);
insert into Person (name, age) VALUES ('Bob', 52);
insert into Person (name, age) VALUES ('Katy', 14);


insert into Item (person_id, item_name) VALUES (1, 'Book');
insert into Item (person_id, item_name) VALUES (1, 'AirPods');
insert into Item (person_id, item_name) VALUES (2, 'Iphone');
insert into Item (person_id, item_name) VALUES (3, 'Kindle');
insert into Item (person_id, item_name) VALUES (3, 'TV');
insert into Item (person_id, item_name) VALUES (3, 'PlayStation');

