drop table Person;

create table Person
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(100) not null,
    age   int,
    email varchar(100)
);

insert into Person(name, age, email)
values ('Tom', 25, 'tom@mail.com');
insert into Person(name, age, email)
values ('Bob', 51, 'bob@mail.com');
insert into Person(name, age, email)
values ('Katy', 38, 'katy@mail.com');

select *
from Person;

alter table Person
    add column created_at  timestamp,
    add column updated_at  timestamp,
    add column created_who varchar;
